title: Zotfile
description: "Zotero plugin to manage your attachments: automatically rename, move, and attach PDFs (or other files) to Zotero items, sync PDFs from your Zotero library to your (mobile) PDF reader (e.g. an iPad, Android tablet, etc.), and extract PDF annotations."
google_analytics: UA-22825629-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
